# configure vscode yaml support https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml
# yaml-language-server: $schema=https://fasterci.com/config.schema.json
workflows:

  - &build_workflow
    name: Faster CI / build (6.0.0)
    env:
      USE_BAZEL_VERSION: "6.0.0"
    on:
      push:
        branches:
          - main
      pull_request:
        branches:
          - "**"
    steps:
      - name: Build & test
        bazel:
          build_targets:
            - //...
          test_targets:
            - //...
      - name: Build & test e2e
        working-directory: e2e
        bazel:
          build_targets:
            - //...
          test_targets:
            - //...

  - <<: *build_workflow
    name: Faster CI / build (6.3.2)
    env:
      USE_BAZEL_VERSION: "6.3.2"
