workflows:

  - &build_workflow
    name: Faster CI / build (6.1.0)
    env:
      USE_BAZEL_VERSION: "6.1.0"
    on:
      push:
        branches:
          - main
      pull_request:
        branches:
          - "**"
    steps:
      - name: Build & test
        bazel:
          build_targets:
            - //...
          test_targets:
            - //...
      - name: Build & test e2e
        working-directory: e2e
        bazel:
          build_targets:
            - //...
          test_targets:
            - //...
          test_flags:
            - --test_size_filters=-large,-enormous

  - <<: *build_workflow
    name: Faster CI / build (6.3.2)
    env:
      USE_BAZEL_VERSION: "6.3.2"
